-- The whole database, for a new Supabase project: paste this file into the
-- SQL Editor and run it, once. (migrations/ is the history of how the
-- original database reached this point; a new one doesn't need it.)
--
-- Only the server touches data, with its secret key. Every table has
-- row-level security on and no policies, and the browser's roles (anon,
-- authenticated) are given nothing, so the publishable key can read nothing.

begin;

create extension if not exists vector with schema extensions;

-- ---------- accounts ----------

create table public.accounts (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id) on delete cascade,
  provider text not null default 'gmail' check (provider in ('gmail', 'imap')),
  email_address text not null,
  display_name text,
  color text,
  -- unchecked accounts still sync; their mail is left out of the inbox and AI search
  show_in_inbox boolean not null default true,
  signature text,
  -- encrypted by the server (AES-256-GCM, key in CREDENTIALS_KEY); never plaintext
  credentials text,
  -- the connector's sync position (Gmail history id, IMAP UIDs per folder)
  sync_state jsonb not null default '{}'::jsonb,
  last_synced_at timestamptz,
  constraint accounts_user_provider_email_key unique (user_id, provider, email_address)
);

-- ---------- messages ----------

create table public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  account_id bigint not null references public.accounts(id) on delete cascade,
  -- Gmail's message id, or "<folder>:<uidValidity>:<uid>" for IMAP
  external_id text not null,
  thread_id text,
  sender text,
  to_recipients text,
  cc_recipients text,
  subject text,
  snippet text,
  body text, -- the first 5000 characters; the whole email is fetched when opened
  received_at timestamptz,
  labels text[] not null default '{}', -- INBOX, SENT, UNREAD, SPAM, CATEGORY_...
  is_read boolean,
  has_attachments boolean not null default false,
  pinned_at timestamptz, -- pins live only in the app
  embedding vector(1536), -- OpenAI text-embedding-3-small, for search by meaning
  -- keyword search; subject matches rank above sender, sender above body
  fts tsvector generated always as (
    setweight(to_tsvector('english', coalesce(subject, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(sender, '')), 'B') ||
    to_tsvector('english', coalesce(body, ''))
  ) stored,
  constraint messages_account_external_key unique (account_id, external_id)
);

create index messages_account_received_idx on public.messages (account_id, received_at desc);
create index messages_thread_idx on public.messages (account_id, thread_id);
create index messages_fts_idx on public.messages using gin (fts);
create index messages_embedding_hnsw_idx on public.messages using hnsw (embedding vector_cosine_ops);
create index messages_pinned_idx on public.messages (account_id, pinned_at desc) where pinned_at is not null;

-- ---------- attachments (details only; files are read from the mailbox when needed) ----------

create table public.attachments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message_id bigint not null references public.messages(id) on delete cascade,
  -- the provider's stable id for the part (Gmail partId, IMAP part number)
  external_id text not null,
  filename text,
  mime_type text,
  size_bytes integer,
  extracted_text text, -- saved the first time the assistant reads it
  unique (message_id, external_id)
);

-- ---------- notes ----------

create table public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null default '',
  -- the user's own order, lowest first; fractional, so moving a note between
  -- two others only rewrites that one note
  position double precision not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index notes_user_position_idx on public.notes (user_id, position);

-- Everything attached to a note is an add-on: a reminder, a link to an email
-- or another note, a pin.
create table public.note_addons (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.notes(id) on delete cascade,
  kind text not null check (kind in ('reminder', 'email_link', 'note_link', 'pin')),
  -- who attached it, so the AI's are marked and can be undone
  added_by text not null default 'user' check (added_by in ('user', 'ai')),
  created_at timestamptz not null default now(),
  remind_at timestamptz,
  done_at timestamptz,
  linked_message_id bigint references public.messages(id) on delete cascade,
  -- a link between two notes is stored once and shown on both
  linked_note_id bigint references public.notes(id) on delete cascade,
  constraint note_addons_reminder_check check (kind <> 'reminder' or remind_at is not null),
  constraint note_addons_email_link_check check (kind <> 'email_link' or linked_message_id is not null),
  constraint note_addons_note_link_check check (kind <> 'note_link' or (linked_note_id is not null and linked_note_id <> note_id))
);

-- at most one reminder and one pin per note, and no duplicate links
create unique index note_addons_one_reminder on public.note_addons (note_id) where kind = 'reminder';
create unique index note_addons_one_pin on public.note_addons (note_id) where kind = 'pin';
create unique index note_addons_unique_email_link on public.note_addons (note_id, linked_message_id) where kind = 'email_link';
create unique index note_addons_unique_note_link on public.note_addons (note_id, linked_note_id) where kind = 'note_link';
create index note_addons_linked_message_idx on public.note_addons (linked_message_id) where linked_message_id is not null;
create index note_addons_linked_note_idx on public.note_addons (linked_note_id) where linked_note_id is not null;

-- ---------- outbox: email waiting out its 15-second undo, or scheduled ----------

create table public.outbox (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  account_id bigint not null references public.accounts(id) on delete cascade,
  status text not null default 'waiting' check (status in ('waiting', 'sending', 'sent', 'failed')),
  send_at timestamptz not null,
  email jsonb, -- the email itself; cleared once sent
  error text, -- why sending failed, shown to the user
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

create index outbox_waiting_idx on public.outbox (send_at) where status = 'waiting';

-- ---------- temp addresses ----------

create table public.temp_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- the connected account its mail is forwarded to
  account_id bigint not null references public.accounts(id) on delete cascade,
  address text not null unique,
  label text not null default '',
  color text,
  show_in_inbox boolean not null default true,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index temp_addresses_user_idx on public.temp_addresses (user_id);
create index temp_addresses_expires_idx on public.temp_addresses (expires_at);

-- ---------- search ----------

-- Search by meaning: the user's accounts among match_account_ids, nearest
-- embeddings first, with optional filters.
create function public.search_messages_semantic(
  query_embedding vector,
  match_user_id uuid,
  match_account_ids bigint[],
  match_count integer default 10,
  sender_filter text default null,
  after_date timestamptz default null,
  before_date timestamptz default null,
  attachments_only boolean default false
)
returns table(
  id bigint, account_id bigint, subject text, sender text, snippet text, body text,
  received_at timestamptz, has_attachments boolean, score double precision
)
language plpgsql
stable
-- how many candidates the index looks at per search (default 40)
set hnsw.ef_search = 100
as $$
#variable_conflict use_column
declare
  owned bigint[] := array(
    select a.id from public.accounts a
    where a.user_id = match_user_id and a.id = any(match_account_ids)
  );
begin
  if sender_filter is null and after_date is null and before_date is null and not attachments_only then
    -- no filters: the index walks straight to the nearest embeddings
    return query
      select m.id, m.account_id, m.subject, m.sender, m.snippet, m.body, m.received_at, m.has_attachments,
             1 - (m.embedding <=> query_embedding)
      from public.messages m
      where m.account_id = any(owned) and m.embedding is not null
      order by m.embedding <=> query_embedding
      limit match_count;
  else
    -- filters: rank only the emails that pass them, exactly. The "+ 0" keeps
    -- Postgres off the index, which would find the nearest emails overall and
    -- then throw away the ones failing the filters, often leaving too few.
    return query
      select m.id, m.account_id, m.subject, m.sender, m.snippet, m.body, m.received_at, m.has_attachments,
             1 - (m.embedding <=> query_embedding)
      from public.messages m
      where m.account_id = any(owned)
        and m.embedding is not null
        and (sender_filter is null or strpos(lower(m.sender), lower(sender_filter)) > 0)
        and (after_date is null or m.received_at >= after_date)
        and (before_date is null or m.received_at < before_date)
        and (not attachments_only or m.has_attachments)
      order by (m.embedding <=> query_embedding) + 0
      limit match_count;
  end if;
end;
$$;

-- Keyword search: every word (or, with match_any, any word), best matches
-- first; with no words, the filtered emails newest first.
create function public.search_messages_keyword(
  search_query text,
  match_user_id uuid,
  match_account_ids bigint[],
  match_count integer default 10,
  match_offset integer default 0,
  match_any boolean default false,
  sender_filter text default null,
  after_date timestamptz default null,
  before_date timestamptz default null,
  attachments_only boolean default false
)
returns table(
  id bigint, account_id bigint, subject text, sender text, snippet text, body text,
  received_at timestamptz, has_attachments boolean, is_read boolean, score double precision
)
language plpgsql
stable
as $$
#variable_conflict use_column
declare
  owned bigint[] := array(
    select a.id from public.accounts a
    where a.user_id = match_user_id and a.id = any(match_account_ids)
  );
  tsq tsquery;
begin
  if coalesce(trim(search_query), '') <> '' then
    tsq := case
      -- plainto_tsquery joins the words with &; swapping in | makes them alternatives
      when match_any then replace(plainto_tsquery('english', search_query)::text, '&', '|')::tsquery
      else websearch_to_tsquery('english', search_query)
    end;
    -- only common words like "the" or "my": nothing to search for
    if numnode(tsq) = 0 then
      return;
    end if;
  end if;

  if tsq is null then
    return query
      select m.id, m.account_id, m.subject, m.sender, m.snippet, m.body, m.received_at, m.has_attachments, m.is_read,
             0::double precision
      from public.messages m
      where m.account_id = any(owned)
        and (sender_filter is null or strpos(lower(m.sender), lower(sender_filter)) > 0)
        and (after_date is null or m.received_at >= after_date)
        and (before_date is null or m.received_at < before_date)
        and (not attachments_only or m.has_attachments)
      order by m.received_at desc nulls last
      limit match_count offset match_offset;
  else
    -- "fts @@ tsq" with tsq as a plain value lets Postgres use the full-text index
    return query
      select m.id, m.account_id, m.subject, m.sender, m.snippet, m.body, m.received_at, m.has_attachments, m.is_read,
             ts_rank_cd(m.fts, tsq)::double precision as rank
      from public.messages m
      where m.account_id = any(owned)
        and m.fts @@ tsq
        and (sender_filter is null or strpos(lower(m.sender), lower(sender_filter)) > 0)
        and (after_date is null or m.received_at >= after_date)
        and (before_date is null or m.received_at < before_date)
        and (not attachments_only or m.has_attachments)
      order by rank desc, m.received_at desc nulls last
      limit match_count offset match_offset;
  end if;
end;
$$;

-- pgvector 0.8+ can keep walking the index when the account filter drops
-- candidates (e.g. with some accounts hidden). Older versions skip this.
do $$
begin
  if (select string_to_array(extversion, '.')::int[] >= array[0, 8, 0] from pg_extension where extname = 'vector') then
    execute 'alter function public.search_messages_semantic(vector, uuid, bigint[], integer, text, timestamptz, timestamptz, boolean)
             set hnsw.iterative_scan = relaxed_order';
  end if;
end $$;

-- ---------- who may do what ----------

alter table public.accounts enable row level security;
alter table public.messages enable row level security;
alter table public.attachments enable row level security;
alter table public.notes enable row level security;
alter table public.note_addons enable row level security;
alter table public.outbox enable row level security;
alter table public.temp_addresses enable row level security;

revoke all on all tables in schema public from anon, authenticated;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

-- Postgres lets anyone run a new function, including the browser's roles
revoke execute on function public.search_messages_semantic(vector, uuid, bigint[], integer, text, timestamptz, timestamptz, boolean)
  from public, anon, authenticated;
revoke execute on function public.search_messages_keyword(text, uuid, bigint[], integer, integer, boolean, text, timestamptz, timestamptz, boolean)
  from public, anon, authenticated;
grant execute on function public.search_messages_semantic(vector, uuid, bigint[], integer, text, timestamptz, timestamptz, boolean)
  to service_role;
grant execute on function public.search_messages_keyword(text, uuid, bigint[], integer, integer, boolean, text, timestamptz, timestamptz, boolean)
  to service_role;

-- ---------- storage ----------

-- files attached to emails being sent, until they're sent (25 MB per email)
insert into storage.buckets (id, name, public, file_size_limit)
values ('outbox-attachments', 'outbox-attachments', false, 26214400)
on conflict (id) do nothing;

commit;
