-- 001: multi-account / multi-provider schema.
-- Run 000_precheck.sql first. Paste this whole file into the Supabase SQL Editor and run it.
-- It runs as one transaction: if any statement fails, nothing is changed.

begin;

-- ---------- accounts ----------

alter table public.accounts
  add column if not exists provider text not null default 'gmail',
  add column if not exists display_name text,
  add column if not exists sync_state jsonb not null default '{}'::jsonb,
  -- encrypted by the server (AES-256-GCM, key in CREDENTIALS_KEY); never plaintext
  add column if not exists credentials text;

alter table public.accounts
  add constraint accounts_provider_check check (provider in ('gmail', 'imap')),
  add constraint accounts_user_provider_email_key unique (user_id, provider, email_address);

-- refresh_token stays for now: the server moves each one into `credentials`
-- (encrypted) the first time it uses the account, then clears it.
-- A later migration drops the column once they're all moved.

-- ---------- messages ----------

alter table public.messages rename column gmail_message_id to external_id;

-- Drop the old "unique across the whole table" rule on that column.
-- Its name isn't known, so look it up rather than guess.
do $$
declare
  col smallint;
  r record;
begin
  select attnum into col
  from pg_attribute
  where attrelid = 'public.messages'::regclass and attname = 'external_id';

  for r in
    select i.indexrelid::regclass as index_name, c.conname
    from pg_index i
    left join pg_constraint c on c.conindid = i.indexrelid and c.conrelid = i.indrelid
    where i.indrelid = 'public.messages'::regclass
      and i.indisunique and not i.indisprimary
      and i.indnatts = 1 and i.indkey[0] = col
  loop
    if r.conname is not null then
      execute format('alter table public.messages drop constraint %I', r.conname);
    else
      execute format('drop index %s', r.index_name);
    end if;
  end loop;
end $$;

alter table public.messages
  add column if not exists thread_id text,
  add column if not exists to_recipients text,
  add column if not exists cc_recipients text,
  add column if not exists labels text[] not null default '{}',
  -- null = unknown (messages synced before this migration)
  add column if not exists is_read boolean,
  add column if not exists has_attachments boolean not null default false,
  -- keyword search; subject matches rank above sender, sender above body
  add column if not exists fts tsvector generated always as (
    setweight(to_tsvector('english', coalesce(subject, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(sender, '')), 'B') ||
    to_tsvector('english', coalesce(body, ''))
  ) stored;

-- unique per account instead of across the whole table
alter table public.messages
  add constraint messages_account_external_key unique (account_id, external_id);

-- deleting an account deletes its messages
alter table public.messages drop constraint if exists messages_account_id_fkey;
alter table public.messages
  add constraint messages_account_id_fkey
  foreign key (account_id) references public.accounts(id) on delete cascade;

create index if not exists messages_account_received_idx on public.messages (account_id, received_at desc);
create index if not exists messages_thread_idx on public.messages (account_id, thread_id);
create index if not exists messages_fts_idx on public.messages using gin (fts);

-- ---------- attachments ----------

create table if not exists public.attachments (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  message_id bigint not null references public.messages(id) on delete cascade,
  -- provider's stable id for the part (Gmail partId). Gmail's attachmentId
  -- changes between requests, so it's looked up fresh when downloading.
  external_id text not null,
  filename text,
  mime_type text,
  size_bytes integer,
  storage_path text,     -- set once the file is downloaded to Supabase Storage
  extracted_text text,   -- set once text is pulled out (PDF text, OCR)
  embedding vector(1536),
  unique (message_id, external_id)
);

-- ---------- security ----------
-- Row-level security with no policies = only the server (service key) can read
-- or write these tables; the public anon key gets nothing. Per-user policies
-- come with the login step.
alter table public.accounts enable row level security;
alter table public.messages enable row level security;
alter table public.attachments enable row level security;

-- ---------- search ----------

drop function if exists public.match_messages(vector, bigint, integer);

-- Searches every account belonging to a user, or only the ones listed in match_account_ids.
create or replace function public.match_messages(
  query_embedding vector,
  match_user_id uuid,
  match_count integer default 10,
  match_account_ids bigint[] default null
)
returns table(
  id bigint,
  account_id bigint,
  subject text,
  sender text,
  body text,
  snippet text,
  received_at timestamptz,
  similarity double precision
)
language sql
stable
as $$
  select
    m.id, m.account_id, m.subject, m.sender, m.body, m.snippet, m.received_at,
    1 - (m.embedding <=> query_embedding) as similarity
  from public.messages m
  join public.accounts a on a.id = m.account_id
  where a.user_id = match_user_id
    and (match_account_ids is null or m.account_id = any(match_account_ids))
    and m.embedding is not null
  order by m.embedding <=> query_embedding
  limit match_count;
$$;

commit;
