-- 008: notes and their add-ons.
-- A note is just text. Everything else (a reminder time, a link to an email or
-- another note, a pin) is an add-on row attached to it, so new kinds of add-on
-- can be introduced later without changing notes.
-- Paste this whole file into the Supabase SQL Editor and run it.

begin;

create table public.notes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  body text not null default '',
  -- the user's own order within a group, lowest first. Fractional, so moving a
  -- note between two others only rewrites that one note.
  position double precision not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  embedding vector(1536) -- filled in later, so the assistant can search notes
);

create index notes_user_position_idx on public.notes (user_id, position);

create table public.note_addons (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.notes(id) on delete cascade,
  kind text not null check (kind in ('reminder', 'email_link', 'note_link', 'pin')),
  -- who attached it, so AI-added ones can be marked and undone
  added_by text not null default 'user' check (added_by in ('user', 'ai')),
  created_at timestamptz not null default now(),

  -- reminder
  remind_at timestamptz,
  done_at timestamptz,
  -- email_link (deleting the email's account removes the link, not the note)
  linked_message_id bigint references public.messages(id) on delete cascade,
  -- note_link: stored once, shown on both notes
  linked_note_id bigint references public.notes(id) on delete cascade,
  -- for future kinds of add-on that need other details
  data jsonb not null default '{}'::jsonb,

  constraint note_addons_reminder_check check (kind <> 'reminder' or remind_at is not null),
  constraint note_addons_email_link_check check (kind <> 'email_link' or linked_message_id is not null),
  constraint note_addons_note_link_check check (kind <> 'note_link' or (linked_note_id is not null and linked_note_id <> note_id))
);

-- at most one reminder and one pin per note, and no duplicate links
create unique index note_addons_one_reminder on public.note_addons (note_id) where kind = 'reminder';
create unique index note_addons_one_pin on public.note_addons (note_id) where kind = 'pin';
create unique index note_addons_unique_email_link on public.note_addons (note_id, linked_message_id) where kind = 'email_link';
create unique index note_addons_unique_note_link on public.note_addons (note_id, linked_note_id) where kind = 'note_link';

-- finding the notes stuck to an email, and the notes linking to a note
create index note_addons_linked_message_idx on public.note_addons (linked_message_id) where linked_message_id is not null;
create index note_addons_linked_note_idx on public.note_addons (linked_note_id) where linked_note_id is not null;

-- Same setup as the other tables: row-level security on with no policies, so
-- only the server can read or write. New tables need the server's access
-- granted explicitly in this project (see 002).
alter table public.notes enable row level security;
alter table public.note_addons enable row level security;
grant select, insert, update, delete on public.notes, public.note_addons to service_role;

do $$
begin
  execute format('grant usage, select on sequence %s to service_role', pg_get_serial_sequence('public.notes', 'id'));
  execute format('grant usage, select on sequence %s to service_role', pg_get_serial_sequence('public.note_addons', 'id'));
end $$;

commit;
