-- 009: the outbox, for sending email with a 15-second undo.
-- Pressing Send stores the email here with send_at 15 seconds away; the server
-- sends it then, unless Undo deletes it first. If the server restarts in
-- between, it sends anything overdue when it starts up and on each cron run.
-- Paste this whole file into the Supabase SQL Editor and run it.

begin;

create table public.outbox (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- the account it's sent from (deleting the account removes its unsent mail)
  account_id bigint not null references public.accounts(id) on delete cascade,
  status text not null default 'waiting'
    check (status in ('waiting', 'sending', 'sent', 'failed')),
  send_at timestamptz not null,
  -- { to, cc, bcc, subject, body, replyToMessageId }. Cleared once sent: the
  -- sent copy lives in the mailbox (and comes back through sync) from then on.
  email jsonb,
  error text, -- why sending failed, shown to the user
  created_at timestamptz not null default now(),
  sent_at timestamptz
);

-- finding waiting mail that is due
create index outbox_waiting_idx on public.outbox (send_at) where status = 'waiting';

-- Same setup as the other tables: row-level security on with no policies, so
-- only the server can read or write (see 002 and 008).
alter table public.outbox enable row level security;
grant select, insert, update, delete on public.outbox to service_role;

do $$
begin
  execute format('grant usage, select on sequence %s to service_role', pg_get_serial_sequence('public.outbox', 'id'));
end $$;

commit;
