-- 011: temporary email addresses.
-- Each is a real forwarder on the mail host (e.g. k7x2m9@aaroncheung.me ->
-- contact@aaroncheung.me) that the server creates, and deletes once it
-- expires. Mail to it arrives through the account it forwards to, so it's an
-- ordinary synced message; the app recognizes it by its To/Cc address.
-- On expiry the forwarder is removed (new mail bounces) and the emails it
-- received are deleted from the app and from the mailbox.
-- Paste this whole file into the Supabase SQL Editor and run it.

begin;

create table public.temp_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  -- the connected account its mail is forwarded to
  account_id bigint not null references public.accounts(id) on delete cascade,
  address text not null unique,
  label text not null default '', -- what it was made for ("pizza coupon"), only shown in the app
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index temp_addresses_user_idx on public.temp_addresses (user_id);
create index temp_addresses_expires_idx on public.temp_addresses (expires_at);

-- Same setup as the other tables: row-level security on with no policies, so
-- only the server can read or write (see 002 and 008).
alter table public.temp_addresses enable row level security;
grant select, insert, update, delete on public.temp_addresses to service_role;

do $$
begin
  execute format('grant usage, select on sequence %s to service_role', pg_get_serial_sequence('public.temp_addresses', 'id'));
end $$;

commit;
